require 'jag/config/lsp'
require 'jag/config/nvim-compe'
require 'jag/config/plugins'
require 'jag/config/telescope'
require 'jag/config/treesitter'
require 'jag/commands/git'
require 'jag/mappings/common'
